# Generated by Django 5.2.5 on 2025-09-23 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='cancellation_amount',
            new_name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='refund',
            name='cancellation_percentage',
        ),
    ]
