# Generated by Django 5.2.5 on 2025-08-28 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_code', models.CharField(max_length=50)),
                ('station_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='arrival_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='train',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='train',
            name='source',
        ),
        migrations.CreateModel(
            name='Trainroute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('day_offset', models.PositiveIntegerField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.station')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
    ]
