# Generated by Django 5.2.5 on 2025-08-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_station_remove_train_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainroute',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='trainroute',
            old_name='train_id',
            new_name='train',
        ),
    ]
