# Generated by Django 5.2.5 on 2025-08-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_station_id_trainroute_station_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainroute',
            name='arrival_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='trainroute',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
