# Generated by Django 5.2.5 on 2025-08-28 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_trainroute_arrival_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainroute',
            name='train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_route', to='core.train'),
        ),
    ]
