# Generated by Django 5.2.5 on 2025-08-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_trainroute_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
