# Generated by Django 5.2.5 on 2025-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_train_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='station_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
