# Generated by Django 5.2.5 on 2025-08-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_station_station_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='schedule_days',
            field=models.CharField(),
        ),
    ]
