# Generated by Django 5.2.5 on 2025-09-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_train_schedule_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forgot_password_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='forgot_password_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
