# Generated by Django 5.2.5 on 2025-09-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_traincoach_seat'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincoach',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
