# Generated by Django 5.2.5 on 2025-09-08 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_traincoach_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traincoach',
            name='price',
        ),
    ]
