# Generated by Django 5.2.5 on 2025-09-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_traincoach_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincoach',
            name='base_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='traincoach',
            name='fare_per_km',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='distance',
            field=models.IntegerField(null=True),
        ),
    ]
