# Generated by Django 5.2.5 on 2025-09-09 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_traincoach_base_price_traincoach_fare_per_km_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_bookings', to='core.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_bookings', to='core.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_age', models.IntegerField()),
                ('passenger_gender', models.CharField(max_length=15)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seat')),
            ],
        ),
    ]
