# Generated by Django 5.2.5 on 2025-09-10 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_passenger_booking_alter_trainroute_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='traincoach',
            name='status',
            field=models.CharField(default='running'),
        ),
    ]
