# Generated by Django 5.2.5 on 2025-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_traincoach_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traincoach',
            name='status',
        ),
        migrations.AddField(
            model_name='train',
            name='status',
            field=models.CharField(default='running'),
        ),
    ]
