# Generated by Django 5.2.5 on 2025-09-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_traincoach_status_train_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='status',
        ),
    ]
