# Generated by Django 5.2.5 on 2025-09-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_train_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.FloatField(null=True),
        ),
    ]
