# Generated by Django 5.2.5 on 2025-09-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_booking_total_fare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='schedule_days',
            field=models.JSONField(default=list),
        ),
    ]
