# Generated by Django 5.2.5 on 2025-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_train_schedule_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
