# Generated by Django 5.2.5 on 2025-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_train_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
