# Generated by Django 5.2.5 on 2025-09-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_train_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traincoach',
            name='capacity',
        ),
    ]
