# Generated by Django 5.2.5 on 2025-09-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_traincoach_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
