# Generated by Django 5.2.5 on 2025-09-17 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_booking_booking_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateField()),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.train')),
            ],
        ),
    ]
