# Generated by Django 5.2.5 on 2025-09-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_traincancellation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traincancellation',
            unique_together={('train', 'cancellation_date')},
        ),
    ]
