# Generated by Django 5.2.5 on 2025-09-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_traincancellation_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
