# Generated by Django 5.2.5 on 2025-09-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_booking_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delay_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='delay_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
