# Generated by Django 5.2.5 on 2025-09-18 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_booking_delay_email_sent_booking_delay_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delay_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.station'),
        ),
    ]
