# Generated by Django 5.2.5 on 2025-09-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_booking_delay_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reroute_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='train_rerouted',
            field=models.BooleanField(default=False),
        ),
    ]
