# Generated by Django 5.2.5 on 2025-09-18 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_booking_reroute_email_sent_booking_train_rerouted'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rerouted_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rerouted_station', to='core.station'),
        ),
    ]
