# Generated by Django 5.2.5 on 2025-09-22 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_booking_rerouted_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='get_off_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boarding', to='core.station'),
        ),
    ]
