# Generated by Django 5.2.5 on 2025-09-22 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_booking_get_off_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='get_off_station',
            new_name='boarding',
        ),
    ]
