# Generated by Django 5.2.5 on 2025-09-22 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_get_off_station_booking_boarding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='boarding',
            new_name='boarding_station',
        ),
        migrations.AddField(
            model_name='booking',
            name='get_off_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_off', to='core.station'),
        ),
    ]
