# Generated by Django 5.2.5 on 2025-09-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_rename_boarding_booking_boarding_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
