# Generated by Django 5.2.5 on 2025-09-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_booking_cancellation_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cancellation_percentage',
        ),
    ]
