# Generated by Django 5.2.5 on 2025-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_booking_cancellation_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
